/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author HP
 */
public class PedirPrioridadOZona extends javax.swing.JFrame
{

    /**
     * Creates new form PedirPrioridad
     */
    public PedirPrioridadOZona()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jlbTexto = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        btnAceptarPrioridad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jlbTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbTexto.setText("TEXTO:");

        jComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jComboBoxKeyPressed(evt);
            }
        });

        btnAceptarPrioridad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAceptarPrioridad.setText("Aceptar");
        btnAceptarPrioridad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarPrioridadActionPerformed(evt);
            }
        });
        btnAceptarPrioridad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnAceptarPrioridadKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jlbTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnAceptarPrioridad)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTexto)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnAceptarPrioridad)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnAceptarPrioridad()
    {
        return btnAceptarPrioridad;
    }

    public void setBtnAceptarPrioridad(JButton btnAceptarPrioridad)
    {
        this.btnAceptarPrioridad = btnAceptarPrioridad;
    }

    public JLabel getJlbTexto()
    {
        return jlbTexto;
    }

    public JComboBox<String> getjComboBox()
    {
        return jComboBox;
    }

    public void setjComboBox(JComboBox<String> jComboBox)
    {
        this.jComboBox = jComboBox;
    }

    public void setJlbTexto(JLabel jLabel1)
    {
        this.jlbTexto = jLabel1;
    }

    private void jComboBoxKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jComboBoxKeyPressed
    {//GEN-HEADEREND:event_jComboBoxKeyPressed
        // TODO add your handling code here:
        ValidacionesExtra.ValidacionesExtra.cambia(KeyEvent.VK_ENTER, evt, btnAceptarPrioridad);
    }//GEN-LAST:event_jComboBoxKeyPressed

    private void btnAceptarPrioridadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarPrioridadActionPerformed
    {//GEN-HEADEREND:event_btnAceptarPrioridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarPrioridadActionPerformed

    private void btnAceptarPrioridadKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAceptarPrioridadKeyPressed
    {//GEN-HEADEREND:event_btnAceptarPrioridadKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnAceptarPrioridad.doClick(); // Simula un clic en el botón
        }
    }//GEN-LAST:event_btnAceptarPrioridadKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PedirPrioridadOZona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PedirPrioridadOZona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PedirPrioridadOZona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PedirPrioridadOZona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PedirPrioridadOZona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarPrioridad;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jlbTexto;
    // End of variables declaration//GEN-END:variables
}
