/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Estructuras.ColaDinamica;
import Estructuras.ListaCircularSL;
import Estructuras.Nodo;
import Modelo.Paciente;
import Modelo.VistaPacientes;
import ValidacionesExtra.ValidacionesExtra;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class VentanaPrincipal extends javax.swing.JFrame implements VistaPacientes
{

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal()
    {
        initComponents();
        CtrlInterfaz.cambia(jtfNumeroPaciente);
        jtbTablaPacientes.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
    }

    public JButton getBtnAtenderPaciente()
    {
        return btnAtenderPaciente;
    }

    public void setBtnAtenderPaciente(JButton btnAtenderPaciente)
    {
        this.btnAtenderPaciente = btnAtenderPaciente;
    }

    public JButton getBtnExcepcionPacientes()
    {
        return btnExcepcionPacientes;
    }

    public void setBtnExcepcionPacientes(JButton btnExcepcionPacientes)
    {
        this.btnExcepcionPacientes = btnExcepcionPacientes;
    }

    public JButton getBtnMoverPaciente()
    {
        return btnMoverPaciente;
    }

    public void setBtnMoverPaciente(JButton btnMoverPaciente)
    {
        this.btnMoverPaciente = btnMoverPaciente;
    }

    public JButton getBtnOrdenarPorZona()
    {
        return btnOrdenarPorZona;
    }

    public void setBtnOrdenarPorZona(JButton btnOrdenarPorZona)
    {
        this.btnOrdenarPorZona = btnOrdenarPorZona;
    }

    public JButton getBtnRegistrarPaciente()
    {
        return btnRegistrarPaciente;
    }

    public void setBtnRegistrarPaciente(JButton btnRegistrarPaciente)
    {
        this.btnRegistrarPaciente = btnRegistrarPaciente;
    }

    public JComboBox<String> getJcbPrioridadPaciente()
    {
        return jcbPrioridadPaciente;
    }

    public void setJcbPrioridadPaciente(JComboBox<String> jcbPrioridadPaciente)
    {
        this.jcbPrioridadPaciente = jcbPrioridadPaciente;
    }

    public JComboBox<String> getJcbZonaPaciente()
    {
        return jcbZonaPaciente;
    }

    public void setJcbZonaPaciente(JComboBox<String> jcbZonaPaciente)
    {
        this.jcbZonaPaciente = jcbZonaPaciente;
    }

    public JTextField getJtfNombrePaciente()
    {
        return jtfNombrePaciente;
    }

    public void setJtfNombrePaciente(JTextField jtfNombrePaciente)
    {
        this.jtfNombrePaciente = jtfNombrePaciente;
    }

    public JTextField getJtfNumeroPaciente()
    {
        return jtfNumeroPaciente;
    }

    public void setJtfNumeroPaciente(JTextField jtfNumeroPaciente)
    {
        this.jtfNumeroPaciente = jtfNumeroPaciente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jtpRegistrarPaciente = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jtfNombrePaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNumeroPaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegistrarPaciente = new javax.swing.JButton();
        jcbZonaPaciente = new javax.swing.JComboBox<>();
        jcbPrioridadPaciente = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnAtenderPaciente = new javax.swing.JButton();
        btnMoverPaciente = new javax.swing.JButton();
        btnOrdenarPorZona = new javax.swing.JButton();
        btnExcepcionPacientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTablaPacientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtpRegistrarPaciente.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jtpRegistrarPacienteFocusGained(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfNombrePaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfNombrePaciente.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtfNombrePacienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtfNombrePacienteKeyTyped(evt);
            }
        });
        jPanel1.add(jtfNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 251, 204, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Numero");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 90, -1, -1));

        jtfNumeroPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfNumeroPaciente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfNumeroPacienteActionPerformed(evt);
            }
        });
        jtfNumeroPaciente.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtfNumeroPacienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtfNumeroPacienteKeyTyped(evt);
            }
        });
        jPanel1.add(jtfNumeroPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 204, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Zona");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 285, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Prioridad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("DATOS DEL PACIENTE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        btnRegistrarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrarPaciente.setText("Registrar");
        btnRegistrarPaciente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistrarPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        jcbZonaPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbZonaPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jcbZonaPaciente.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcbZonaPacienteKeyPressed(evt);
            }
        });
        jPanel1.add(jcbZonaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jcbPrioridadPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbPrioridadPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jcbPrioridadPaciente.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcbPrioridadPacienteKeyPressed(evt);
            }
        });
        jPanel1.add(jcbPrioridadPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jtpRegistrarPaciente.addTab("Recepcion Pacientes", jPanel1);

        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtenderPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtenderPaciente.setText("Atender Paciente");
        btnAtenderPaciente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAtenderPacienteActionPerformed(evt);
            }
        });
        btnAtenderPaciente.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnAtenderPacienteKeyPressed(evt);
            }
        });
        jPanel2.add(btnAtenderPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 152, -1));

        btnMoverPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMoverPaciente.setText("Mover Pacientes");
        btnMoverPaciente.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnMoverPacienteKeyPressed(evt);
            }
        });
        jPanel2.add(btnMoverPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 152, -1));

        btnOrdenarPorZona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOrdenarPorZona.setText("Ordenar Por Zona");
        btnOrdenarPorZona.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOrdenarPorZonaActionPerformed(evt);
            }
        });
        btnOrdenarPorZona.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnOrdenarPorZonaKeyPressed(evt);
            }
        });
        jPanel2.add(btnOrdenarPorZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 152, -1));

        btnExcepcionPacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcepcionPacientes.setText("Excepcion Pacientes");
        btnExcepcionPacientes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExcepcionPacientesActionPerformed(evt);
            }
        });
        btnExcepcionPacientes.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnExcepcionPacientesKeyPressed(evt);
            }
        });
        jPanel2.add(btnExcepcionPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 30, 152, -1));

        jtbTablaPacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbTablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Numero", "Prioridad", "Nombre", "Zona"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jtbTablaPacientes.setEnabled(false);
        jtbTablaPacientes.setFocusable(false);
        jtbTablaPacientes.setGridColor(new java.awt.Color(204, 204, 204));
        jtbTablaPacientes.setRowHeight(22);
        jtbTablaPacientes.setSelectionBackground(new java.awt.Color(255, 255, 102));
        jtbTablaPacientes.getTableHeader().setReorderingAllowed(false);
        jtbTablaPacientes.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jtbTablaPacientes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 700, 370));

        jtpRegistrarPaciente.addTab("Ver Pacientes", jPanel2);

        getContentPane().add(jtpRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenarPorZonaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOrdenarPorZonaActionPerformed
    {//GEN-HEADEREND:event_btnOrdenarPorZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrdenarPorZonaActionPerformed

    private void btnAtenderPacienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAtenderPacienteActionPerformed
    {//GEN-HEADEREND:event_btnAtenderPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtenderPacienteActionPerformed

    private void btnExcepcionPacientesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExcepcionPacientesActionPerformed
    {//GEN-HEADEREND:event_btnExcepcionPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcepcionPacientesActionPerformed

    private void jtfNumeroPacienteKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfNumeroPacienteKeyPressed
    {//GEN-HEADEREND:event_jtfNumeroPacienteKeyPressed
        // TODO add your handling code here:

        ValidacionesExtra.validaCopyPaste(evt);
        ValidacionesExtra.cambia(KeyEvent.VK_ENTER,evt, jcbPrioridadPaciente);


    }//GEN-LAST:event_jtfNumeroPacienteKeyPressed

    private void jtfNumeroPacienteKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfNumeroPacienteKeyTyped
    {//GEN-HEADEREND:event_jtfNumeroPacienteKeyTyped
        // TODO add your handling code here:
        Validaciones.validaEntero(evt);
        ValidacionesExtra.validaLongitud(evt, jtfNumeroPaciente.getText(), 5);


    }//GEN-LAST:event_jtfNumeroPacienteKeyTyped

    private void jtfNombrePacienteKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfNombrePacienteKeyTyped
    {//GEN-HEADEREND:event_jtfNombrePacienteKeyTyped
        // TODO add your handling code here:
        Validaciones.validaAlfabeticos(evt);
        ValidacionesExtra.validaLongitud(evt, jtfNombrePaciente.getText(), 50);
    }//GEN-LAST:event_jtfNombrePacienteKeyTyped

    private void jtfNumeroPacienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfNumeroPacienteActionPerformed
    {//GEN-HEADEREND:event_jtfNumeroPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumeroPacienteActionPerformed

    private void jtfNombrePacienteKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfNombrePacienteKeyPressed
    {//GEN-HEADEREND:event_jtfNombrePacienteKeyPressed
        // TODO add your handling code here:
        ValidacionesExtra.validaCopyPaste(evt);
        ValidacionesExtra.cambia(KeyEvent.VK_ENTER,evt, jcbZonaPaciente);
    }//GEN-LAST:event_jtfNombrePacienteKeyPressed

    private void btnRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistrarPacienteActionPerformed
    {//GEN-HEADEREND:event_btnRegistrarPacienteActionPerformed

        if (jtfNombrePaciente.getText().trim().length() == 0 || jtfNumeroPaciente.getText().trim().length() == 0)
        {
            Mensajes.error(this, "Debe llenar todos los campos");
            CtrlInterfaz.cambia(jtfNumeroPaciente);
            return;
        }
        Mensajes.exito(this, "Registro exitoso");
        CtrlInterfaz.limpia(jtfNombrePaciente, jtfNumeroPaciente);
        jcbPrioridadPaciente.setSelectedIndex(0);
        jcbZonaPaciente.setSelectedIndex(0);
        CtrlInterfaz.cambia(jtfNumeroPaciente);
    }//GEN-LAST:event_btnRegistrarPacienteActionPerformed

    private void jcbPrioridadPacienteKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcbPrioridadPacienteKeyPressed
    {//GEN-HEADEREND:event_jcbPrioridadPacienteKeyPressed
        // TODO add your handling code here:
        ValidacionesExtra.cambia(KeyEvent.VK_ENTER,evt, jtfNombrePaciente);
    }//GEN-LAST:event_jcbPrioridadPacienteKeyPressed

    private void jcbZonaPacienteKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcbZonaPacienteKeyPressed
    {//GEN-HEADEREND:event_jcbZonaPacienteKeyPressed
        // TODO add your handling code here:
        ValidacionesExtra.cambia(KeyEvent.VK_ENTER,evt, btnRegistrarPaciente);
    }//GEN-LAST:event_jcbZonaPacienteKeyPressed

    private void jtpRegistrarPacienteFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtpRegistrarPacienteFocusGained
    {//GEN-HEADEREND:event_jtpRegistrarPacienteFocusGained
        // TODO add your handling code here:
        CtrlInterfaz.cambia(btnAtenderPaciente);
    }//GEN-LAST:event_jtpRegistrarPacienteFocusGained

    private void btnAtenderPacienteKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAtenderPacienteKeyPressed
    {//GEN-HEADEREND:event_btnAtenderPacienteKeyPressed
        // TODO add your handling code here:
        ValidacionesExtra.cambia(KeyEvent.VK_RIGHT, evt, btnMoverPaciente);
        ValidacionesExtra.cambia(KeyEvent.VK_LEFT, evt, btnOrdenarPorZona);
    }//GEN-LAST:event_btnAtenderPacienteKeyPressed

    private void btnMoverPacienteKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnMoverPacienteKeyPressed
    {//GEN-HEADEREND:event_btnMoverPacienteKeyPressed
        // TODO add your handling code here:
        ValidacionesExtra.cambia(KeyEvent.VK_RIGHT, evt, btnExcepcionPacientes);
        ValidacionesExtra.cambia(KeyEvent.VK_LEFT, evt, btnAtenderPaciente);
    }//GEN-LAST:event_btnMoverPacienteKeyPressed

    private void btnExcepcionPacientesKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnExcepcionPacientesKeyPressed
    {//GEN-HEADEREND:event_btnExcepcionPacientesKeyPressed
        // TODO add your handling code here:
        ValidacionesExtra.cambia(KeyEvent.VK_RIGHT, evt, btnOrdenarPorZona);
        ValidacionesExtra.cambia(KeyEvent.VK_LEFT, evt, btnMoverPaciente);
    }//GEN-LAST:event_btnExcepcionPacientesKeyPressed

    private void btnOrdenarPorZonaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnOrdenarPorZonaKeyPressed
    {//GEN-HEADEREND:event_btnOrdenarPorZonaKeyPressed
        // TODO add your handling code here:
        ValidacionesExtra.cambia(KeyEvent.VK_RIGHT, evt,btnAtenderPaciente);
        ValidacionesExtra.cambia(KeyEvent.VK_LEFT, evt, btnExcepcionPacientes);
    }//GEN-LAST:event_btnOrdenarPorZonaKeyPressed
    @Override
    public void mostrarTodosLosPacientesPorPrioridad(ListaCircularSL pacientes)
    {
        if (pacientes == null)
        {
            Mensajes.error(this, "La lista no existe");
            return;
        }
        if (pacientes.getR() == null)
        {
            Mensajes.error(this, "La lista esta vacia");
            return;
        }
        Nodo<ColaDinamica> aux = pacientes.getR().getSiguiente();
        do
        {
            ponerColaEnTabla(aux.getObj());

            aux = aux.getSiguiente();

        } while (aux != pacientes.getR().getSiguiente());

    }

    private void ponerColaEnTabla(ColaDinamica colaPacientes)
    {
        if (colaPacientes == null)
        {
            Mensajes.error(this, "La cola no existe");
            return;
        }
        if (colaPacientes.getAtras() == null)
        {
            Mensajes.error(this, "La cola no tiene pacientes");
            return;
        }
        Nodo<Paciente> aux = colaPacientes.getFrente();
        while (aux != null)
        {
            mostrarPacienteEnTabla(aux.getObj());
            aux = aux.getSiguiente();
        }

    }

    private void mostrarPacienteEnTabla(Paciente paciente)
    {
        if (paciente == null)
        {
            Mensajes.error(this, "El paciente es nulo");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jtbTablaPacientes.getModel();  // Obtener el modelo de la tabla
        Object[] nuevaFila =
        {
            paciente.getNumeroPaciente(), paciente.getPrioridad(), paciente.getNombrePaciente(), paciente.getZona()
        };
        model.addRow(nuevaFila);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtenderPaciente;
    private javax.swing.JButton btnExcepcionPacientes;
    private javax.swing.JButton btnMoverPaciente;
    private javax.swing.JButton btnOrdenarPorZona;
    private javax.swing.JButton btnRegistrarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbPrioridadPaciente;
    private javax.swing.JComboBox<String> jcbZonaPaciente;
    private javax.swing.JTable jtbTablaPacientes;
    private javax.swing.JTextField jtfNombrePaciente;
    private javax.swing.JTextField jtfNumeroPaciente;
    private javax.swing.JTabbedPane jtpRegistrarPaciente;
    // End of variables declaration//GEN-END:variables
}
