/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Estructuras.ColaDinamica;
import Estructuras.ListaCircularSL;
import Estructuras.Nodo;
import Modelo.Clinica;
import Modelo.Paciente;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class VentanaPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal()
    {
        initComponents();
        jtbTablaPacientes.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        Clinica clinica=new Clinica();
        for (int i = 0; i < 10; i++)
        {
            clinica.recepcionPaciente(new Paciente(123, "Juan", 2, 6));
            
        }
        for (int i = 0; i < 10; i++)
        {
            clinica.recepcionPaciente(new Paciente(123, "Maria", 1, 1));
            
        }
        for (int i = 0; i < 5; i++)
        {
            clinica.recepcionPaciente(new Paciente(0000, "Pedro", 1, 8));
            
        }

        mostrarTodosLosPacientes(clinica.getPrioridades());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jtpRegistrarPaciente = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jtfNombrePaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNumeroPaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfZonaPaciente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfPrioridadPaciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAtenderPaciente = new javax.swing.JButton();
        btnMoverPaciente = new javax.swing.JButton();
        btnOrdenarPorZona = new javax.swing.JButton();
        btnExcepcionPacientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTablaPacientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jtfNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 251, 204, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Numero");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 90, -1, -1));
        jPanel1.add(jtfNumeroPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 121, 204, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Zona");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 285, -1, -1));

        jtfZonaPaciente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfZonaPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jtfZonaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 322, 204, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Prioridad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 155, -1, -1));

        jtfPrioridadPaciente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfPrioridadPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jtfPrioridadPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 186, 204, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("DATOS DEL PACIENTE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jButton1.setText("Registrar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 395, -1, -1));

        jtpRegistrarPaciente.addTab("Recepcion Pacientes", jPanel1);

        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtenderPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtenderPaciente.setText("Atender Paciente");
        btnAtenderPaciente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAtenderPacienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnAtenderPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 152, -1));

        btnMoverPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMoverPaciente.setText("Mover Pacientes");
        jPanel2.add(btnMoverPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 152, -1));

        btnOrdenarPorZona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOrdenarPorZona.setText("Ordenar Por Zona");
        btnOrdenarPorZona.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOrdenarPorZonaActionPerformed(evt);
            }
        });
        jPanel2.add(btnOrdenarPorZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 152, -1));

        btnExcepcionPacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcepcionPacientes.setText("Excepcion Pacientes");
        btnExcepcionPacientes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExcepcionPacientesActionPerformed(evt);
            }
        });
        jPanel2.add(btnExcepcionPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 30, 152, -1));

        jtbTablaPacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbTablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Numero", "Prioridad", "Nombre", "Zona"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jtbTablaPacientes.setEnabled(false);
        jtbTablaPacientes.setFocusable(false);
        jtbTablaPacientes.setGridColor(new java.awt.Color(204, 204, 204));
        jtbTablaPacientes.setRowHeight(22);
        jtbTablaPacientes.setSelectionBackground(new java.awt.Color(255, 255, 102));
        jtbTablaPacientes.getTableHeader().setReorderingAllowed(false);
        jtbTablaPacientes.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jtbTablaPacientes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 700, 370));

        jtpRegistrarPaciente.addTab("Ver Pacientes", jPanel2);

        getContentPane().add(jtpRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenarPorZonaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOrdenarPorZonaActionPerformed
    {//GEN-HEADEREND:event_btnOrdenarPorZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrdenarPorZonaActionPerformed

    private void btnAtenderPacienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAtenderPacienteActionPerformed
    {//GEN-HEADEREND:event_btnAtenderPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtenderPacienteActionPerformed

    private void jtfPrioridadPacienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfPrioridadPacienteActionPerformed
    {//GEN-HEADEREND:event_jtfPrioridadPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrioridadPacienteActionPerformed

    private void jtfZonaPacienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfZonaPacienteActionPerformed
    {//GEN-HEADEREND:event_jtfZonaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfZonaPacienteActionPerformed

    private void btnExcepcionPacientesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExcepcionPacientesActionPerformed
    {//GEN-HEADEREND:event_btnExcepcionPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcepcionPacientesActionPerformed
    public void mostrarTodosLosPacientes(ListaCircularSL pacientes)
    {
        if (pacientes == null)
        {
            Mensajes.error(this, "La lista no existe");
            return;
        }
        if (pacientes.getR() == null)
        {
            Mensajes.error(this, "La lista esta vacia");
            return;
        }
        Nodo<ColaDinamica> aux = pacientes.getR().getSiguiente();
        do
        {
            ponerColaEnTabla(aux.getObj());

            aux = aux.getSiguiente();

        } while (aux != pacientes.getR().getSiguiente());

    }

    private void ponerColaEnTabla(ColaDinamica colaPacientes)
    {
        if (colaPacientes == null)
        {
            Mensajes.error(this, "La cola no existe");
            return;
        }
        if (colaPacientes.getAtras() == null)
        {
            Mensajes.error(this, "La cola no tiene pacientes");
            return;
        }
        Nodo<Paciente> aux = colaPacientes.getFrente();
        while (aux != null)
        {
            mostrarPacienteEnTabla(aux.getObj());
            aux = aux.getSiguiente();
        }

    }

    private void mostrarPacienteEnTabla(Paciente paciente)
    {
        if (paciente == null)
        {
            Mensajes.error(this, "El paciente es nulo");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jtbTablaPacientes.getModel();  // Obtener el modelo de la tabla
        Object[] nuevaFila =
        {
            paciente.getNumeroPaciente(), paciente.getPrioridad(), paciente.getNombrePaciente(), paciente.getZona()
        };
        model.addRow(nuevaFila);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtenderPaciente;
    private javax.swing.JButton btnExcepcionPacientes;
    private javax.swing.JButton btnMoverPaciente;
    private javax.swing.JButton btnOrdenarPorZona;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbTablaPacientes;
    private javax.swing.JTextField jtfNombrePaciente;
    private javax.swing.JTextField jtfNumeroPaciente;
    private javax.swing.JTextField jtfPrioridadPaciente;
    private javax.swing.JTextField jtfZonaPaciente;
    private javax.swing.JTabbedPane jtpRegistrarPaciente;
    // End of variables declaration//GEN-END:variables
}
